config/routes.rb
Rails.application.routes.draw do
  root to: 'restaurants#index'
  resources :flats
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def new
    @new_flat = Flat.new
  end

  def create
    strong_params = params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
    @new_flat = Flat.new(strong_params)
    if @new_flat.save
      redirect_to flat_path(@new_flat)
    else
      render :new
    end
  end

  def edit
    @flat = Flat.find(params[:id])
  end

  def update
    strong_params = params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
    @flat = Flat.update(strong_params)

    if @flat.save
      redirect_to show_flat_path(@flat)
    else
      render :edit
    end
  end

  def destroy
    @flat = Flat.find(params[:id])
    Flat.destroy(@flat)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/edit.html.erb
<h1>Flats#edit</h1>
<p>Find me in app/views/flats/edit.html.erb</p>

app/views/flats/index.html.erb
<div class="container mb-3">
  <div class="justify-content-end mb-3">
    <h1>Flats</h1>
  </div>

   <div class="cards">
    <% @flats.each do |flat| %>
    <div class="card-body">
      <img class = "flat-card-image" src="https://images.unsplash.com/photo-1469022563428-aa04fef9f5a2?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1953&q=80" alt="apartment">
      <p><%= flat.name %></p>
      <p><%= flat.address %></p>
      <p><%= flat.description %></p>
      <p>Rates: $<%= flat.price_per_night %></p>
      <p>Price: <%= flat.number_of_guests %></p>
      <div class="row justify-content-between">
        <p><%= link_to "More info", flat_path(flat)%></p>
        <p><%= link_to "Edit", flat_path(flat)%></p>
        <p><%= link_to "Delete", flat_path(flat)%></p>
      </div>
    </div>
  <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<h1>Flats#new</h1>
<p>Find me in app/views/flats/new.html.erb</p>

app/views/flats/show.html.erb
  <div class="justify-content-end mb-3">
    <h1>Flats</h1>
  </div>

   <div class="container">
      <img class = "flat-card-image" src="https://images.unsplash.com/photo-1469022563428-aa04fef9f5a2?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1953&q=80" alt="apartment">
      <p><%= @flat.name %></p>
      <p><%= @flat.address %></p>
      <p><%= @flat.description %></p>
      <p>Rates: $<%= @flat.price_per_night %></p>
      <p>Price: <%= @flat.number_of_guests %></p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to 'My Flats', flats_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item <%= current_page?(root_path) && 'active' %>">
        <%= link_to 'Home', flats_path, class: 'nav-link' %>
      </li>
    </ul>
  </div>
</nav>